name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: rolling
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.6
        with:
          package-name: plansys2_upf_plan_solver
          target-ros2-distro: humble
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          repo-file-url: ${GITHUB_WORKSPACE}/dependencies.repos
