name: jazzy

on:
  pull_request:
    branches:
      - jazzy-devel
  push:
    branches:
      - jazzy-devel
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: jazzy
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install python dep
        run: |
          python3 -m pip install -r upf_solver/requirements.txt
        
      - name: build
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          package-name: upf_solver
          target-ros2-distro: jazzy
          
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          package-name: plansys2_upf_plan_solver
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          vcs-repo-file-url: https://raw.githubusercontent.com/JRL-CARI-CNR-UNIBS/plansys2_upf_plugin/jazzy-devel/dependencies.repos
          import-token: ${{ secrets.GITHUB_TOKEN }}
          rosdep-check: true
          
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

